### ISSUE TITLE
HUD excessive binding of resize listeners

### ISSUE THREAD

**Issue by benjamminf** [pixelandtonic/Garnish#4]
https://github.com/pixelandtonic/garnishjs/blob/develop/src/HUD.js#L406

Not sure the purpose of binding the resize listener in the `updateSizeAndPosition` method, as every time it's called a new event is added, causing the performance of the UI to slow to a crawl very quickly. Removing these lines seems to make everything work fine (in context of Craft's CP) as the listener is already bound in the `init` method.

**Comment by brandonkelly** [comment]
This was fixed via 4d2c01c432df41427df7d368ef058974f620b5a0
