### ISSUE TITLE
How call/listen onAfterAction from BaseElementIndex

### ISSUE THREAD

**Issue by andrelopez** [pixelandtonic/Garnish#5]
Hi folks!

I'm trying to call/listen onAfterAction from my class that extends `Garnish.Base.extend({ ...`

If that possible? I just need to call: `Craft.elementIndex.updateElements();` after an custom element action is finished.

Thanks in advance.

FYI: Craft3 environment

**Comment by andrelopez** [comment]
I have solved the issue listening the `afterAction` function

`Craft.elementIndex.on('afterAction', this.manageAfter);`

**Comment by brandonkelly** [comment]
Glad you figured it out!
