### ISSUE TITLE
Add ability to only close modals by button interactions.

### ISSUE THREAD

**Issue by ryanpcmcquen** [pixelandtonic/Garnish#7]
Currently, clicking outside of a modal causes it to close and erase any unsaved work. It'd be nice if this was at least configurable.

**Comment by andris-sevcenko** [comment]
You can already disable this behavior by setting the [hideOnShadeClick setting](https://github.com/pixelandtonic/garnishjs/blob/develop/src/Modal.js#L325) to false.

**Comment by ryanpcmcquen** [comment]
@andris-sevcenko, that's not modifiable on Craft CMS though, is it?

**Comment by andris-sevcenko** [comment]
It's not possible to transfer issues between organizations on GitHub. Can you please open a new issue in `craftcms/cms`, if you were looking for a Craft setting?

**Comment by ryanpcmcquen** [comment]
@andris-sevcenko, thank you. I have one there with a workaround:

https://github.com/craftcms/cms/issues/4610

PR:
https://github.com/craftcms/cms/pull/4611

But perhaps that PR should be changed to use the `hideOnShadeClick` prop you mentioned. I will rework it in the morning to use that. Thank you!
